# Generated by Django 3.1.5 on 2021-01-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=300)),
                ('crew', models.CharField(blank=True, max_length=255)),
                ('passengers', models.CharField(blank=True, max_length=50)),
                ('cargo_capacity', models.PositiveBigIntegerField(blank=True)),
                ('consumables', models.CharField(max_length=100)),
                ('hyperdrive_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('starship_class', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
